### ISSUE TITLE
Can't set MaxRdyCount! 

### ISSUE THREAD

**Issue by Gigibit** [sproutsocial/nsq-j#18]
Hi, 
I'm using I use your library for a while, but now I need to set maxRdyCount property of nsq subscribtion, and setting maxInFlight doesn't seems to change fixed 2500 maxRdyCount value.

How can I do?

**Comment by robseed** [comment]
You can set the default maxInFlight to use before subscribing
```java
Subscriber subscriber = new Subscriber("lookup-host-1", "lookup-host-2");
subscriber.setDefaultMaxInFlight(100);
//subscriber.subscribe( ...
 ```
or you can set it after subscribing
```java
subscriber.subscribe("topic", "channel", foo::handler);
subscriber.setMaxInFlight("topic", "channel", 100);
```

maxInFlight is used to determine RDY. If maxInFlight is 100 and a topic is being produced on 2 servers, then each server gets RDY 50.

**Comment by Gigibit** [comment]
Thanks a lot!

Il giorno mer 20 giu 2018 alle 21:10 Rob Seed <notifications@github.com> ha
scritto:
