### ISSUE TITLE
[bug?] Application could not terminate correctly

### ISSUE THREAD

**Issue by zhshuai1** [sproutsocial/nsq-j#20]
When I use the sample code to publish message in README.md, I found the application could not terminate correctly. The following is my code:
```java
    public void putMessage(String message) {
        Publisher publisher = new Publisher("localhost");
        byte[] data = "Hello nsq".getBytes();
        publisher.publish("example_topic", data);
        publisher.stop();
        //publisher.getClient().stop();
    }
```
I found this is due to client is not stopped when publisher is stopped. When I call ```publisher.getClient().stop();``` explicitly, the application could terminate correctly.

It does not make sense that I did not use a client, but I should close it(I used publisher only). I think this should be fixed.

**Comment by LinkinStars** [comment]
I had the same problem. I didn't understand why the sender was designed like this.

**Comment by LinkinStars** [comment]
I had the same problem. I didn't understand why the sender was designed like this.
call  publisher.getClient().stop();  is correctly

**Comment by robseed** [comment]
Thanks for your input, we will add the ability to stop the publisher independently in the next release.

**Comment by robseed** [comment]
This should work now, but if you do anything more than create one Publisher you need to
`Client.getDefaultClient().stop()`
