### ISSUE TITLE
I don't know whether the sending is successful.

### ISSUE THREAD

**Issue by LinkinStars** [sproutsocial/nsq-j#22]
In README, I see "Publishes synchronously and returns after nsqd responds OK"
But there is no return value using the publish method. 
I don't know whether the sending is successful.

**Comment by ulaskeles** [comment]
@LinkinStars, `publish` method does publishing synchronously and if it returns without any exceptions thrown then it published the message successfully.

In a case like your `nsqd` or `nsqlookupd` is down and the message is not published, `publish` method will throw an `NSQException`. This exception is thrown as a result of not getting `OK` from `nsqd`. You should only check unsuccessful events by catching the exception.

**Comment by robseed** [comment]
Right, it throws an exception if the message is not published, including when there is a network timeout.
