### ISSUE TITLE
Nsq-j client blocks until maxWaitForShutdown on shutdown due to bad nsqd connections

### ISSUE THREAD

**Issue by jferretti-life** [sproutsocial/nsq-j#26]
Hello. I am fairly new to this nsq-j client, and I ran into an issue when shutting down my service. The problem occurs when nsqlookupd contains an address for a nsqd service that is not network accessible to my service (I get java.net.UnknownHostException). When this is the case, my service (the nsq-j client) freezes until the shutdown timeout value is reached.

My service subscribes to a single topic, on a single channel. The nsqlookupd service has two nsqd services registered for the topic, and one of the services is accessible (GOOD_NSQD) to my service, and the other one is not (BAD_NSQD).

Upon looking at the code for Subscription, I see the following:

From Subscription:
```
public synchronized void checkConnections(Set<HostAndPort> activeHosts) {
...
  for (HostAndPort activeHost : activeHosts) {
      if (!connectionMap.containsKey(activeHost)) {
          try {
              logger.info("adding new connection:{} topic:{}", activeHost, topic);
              SubConnection con = new SubConnection(client, activeHost, this);
              con.connect(subscriber.getConfig());
              connectionMap.put(activeHost, con);
          }
          catch (Exception e) {
              logger.error("error connecting to:{}", activeHost, e);
          }
      }
  }
...
}
```

The `connectionMap` does not contain my BAD_NSQD connection, so it creates a new SubConnection. The `SubConnection.connect()` fails with an IOException, so the connection is never added to the connectionMap. This seems correct, until I noticed the first line of `SubConnection.connect()`:

From SubConnection:
```
public synchronized void connect(Config config) throws IOException {
    client.addSubConnection(this);
    super.connect(config);        // throws IOException
```

The first line of `connect()` adds the SubConnection to the client's subConnection set. The second line, throws the IOException. Nothing removes the bad connection from the Client.

Over time, the client's connection set becomes filled with BAD_NSQD SubConnections.

On shutdown, the `Client.stopSubscribers()` method blocks, waiting until `Client.subConnections` is empty, which it never becomes due to the bad connections. The `Subscription.stop()` method closes only the connections in its `connectionMap`, which do not include the failed connections.

What actually happens:
`Client.stop()` blocks until maxWaitForShutdown on shutdown due to bad nsqd connections

What I expect to happen:
I expect the nsq-j client to gracefully terminate after all in-flight messages are emptied out.

100% reproducible.

1. run a nsqlookupd that is network accessible to your service
2. run a nsqd that is network accessible to your service
3. run a nsqd that is accessible to nsqlookupd, but not your service
4. Run your nsq-j service that consumes a single topic. In my case, I have 1 consumer thread, and 25 in-flight, with a maxWaitForShutdown set to 5 minutes. The nsq-j service invokes `Client.stop()` the service is shutdown.
5. From your terminal, kill your nsq-j service (e.g. kill -INT <java process id>)
6. Notice the following in the logs:

```
2020-01-06 20:08:24.092 [INFO ]    23 --- [extShutdownHook] c.s.n.Client                             : stopping nsq client
2020-01-06 20:08:24.093 [INFO ]    23 --- [extShutdownHook] c.s.n.Subscriber                         : subscriber stopped
2020-01-06 20:08:24.093 [INFO ]    23 --- [extShutdownHook] c.s.n.Client                             : waiting for subscribers to finish in-flight messages
```

**Comment by jferretti-life** [comment]
I have a proposed solution to this issue, including test cases. Let me know if you would like any changes. The changes fixed my memory leak, as well as fixed the shutdown problem. 

I hadn't realized before that the `SubConnection`'s constructor registered a repeating task with the scheduler. The proposed fix is to just ensure `close()` is invoked on both the `SubConnection` and `PubConnection`, even in the event of error on `connect()`.

https://github.com/sproutsocial/nsq-j/pull/28

**Comment by robseed** [comment]
Merged the PR, should be fixed
